server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment


eureka:
  client:
    #表示是否向注册中心注册自己
    register-with-eureka: true
    #是否从eurekaservice抓取已有的注册信息 默认为true 单节点无所谓，集群必须使用true才能配合ribbon使用负载均衡
    fetch-registry: true
    #（入住）注册的地址
    service-url:
     defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka  #集群版
